eureka:
  client:
    serviceUrl:
      defaultZone: http://river:River&&2018@10.39.31.36:9999/eureka/
spring:
  http:
    multipart:
      enabled: true
      file-size-threshold: 500KB
      location: /data/web/tmp
      max-file-size: 500MB
      max-request-size: 1000MB
      resolve-lazily: true
  session:
    store-type: none
  redis:
    host: 10.39.32.42
    port: 6379
    password: river&River2018    
  datasource:
    name: river
    url: jdbc:mysql://10.39.31.27/river?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: river_u
    password: River2018&    
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.cj.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20    
feign:
  service:
    res: res
    bbs: bbs
    business: business
    cms: cms
    dfs: dfs
    project: project
    system: system        
riverLogFilter:
  logIpAddress: 192.168.1.251
  port: 5426
#eureka.client.serviceUrl.defaultZone=http://peer1:1111/eureka/,http://peer2:1112/eureka/    