server:
  port: 9999

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.39.31.36:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: eureka-server1  
security:
  user:
    name: river 
    password: River&&2018      