server:
  port: 8012
spring:  
  datasource:
    url: jdbc:mysql://10.39.31.27/river_business?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  mail:
    host: smtp.xinaogroup.com
    username: ifn@enn.cn
    password: B-AU966G 
    port: 25
    test: false
    properties:
      mail:
        smtp:
          auth: true
          #starttls:
          #  enable: true
          #  required: true         
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  activiti:
    business: http://10.39.31.80:8080/monitor/business  
    SSO: http://10.39.31.80:8081/river-enn-sso     